const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.TheFlashGameEvents_Event33,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{Cidade: 0},
	{Plataforma: 0},
	{BoundTo: 0},
	{CentrarEm: 0},
	{Zoom: 0},
	{Teclado: 0},
	{Sólido: 0},
	{PisoEscuro: 0},
	{VelocidadeNormal: 0},
	{VelocidadeBoost: 0},
	{Flash: 0},
	{Áudio: 0},
	{CidadeEscura: 0},
	{FlorestaEscura: 0},
	{CidadeClaraLago: 0},
	{PisoClaro: 0},
	{CidadeClara: 0},
	{FlorestaClara: 0},
	{RaioVelocidade: 0},
	{RaioLerdeza: 0},
	{Caixotes: 0},
	{FonteDeSprites: 0},
	{Mouse: 0},
	{VelocidadeY: 0},
	{RestritoAoLayout: 0},
	{Sprite: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Projétil: 0},
	{Sprite4: 0},
	{FonteDeSprites2: 0},
	{Texto: 0},
	{Sprite5: 0},
	{Sprite8: 0},
	{MuteDesmute: 0},
	{Constrols: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{CORRIDAFINAL: 0},
	{Âncora: 0},
	{Milesimos: 0},
	{Segundos: 0},
	{Tempo: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Texto2: 0},
	{TempFinal: 0}
];

self.InstanceType = {
	Cidade: class extends self.ITiledBackgroundInstance {},
	Zoom: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	PisoEscuro: class extends self.ISpriteInstance {},
	Flash: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	CidadeEscura: class extends self.ITiledBackgroundInstance {},
	FlorestaEscura: class extends self.ITiledBackgroundInstance {},
	CidadeClaraLago: class extends self.ITiledBackgroundInstance {},
	PisoClaro: class extends self.ITiledBackgroundInstance {},
	CidadeClara: class extends self.ITiledBackgroundInstance {},
	FlorestaClara: class extends self.ITiledBackgroundInstance {},
	RaioVelocidade: class extends self.ISpriteInstance {},
	RaioLerdeza: class extends self.ISpriteInstance {},
	Caixotes: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	MuteDesmute: class extends self.ISpriteInstance {},
	Constrols: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	CORRIDAFINAL: class extends self.ISpriteFontInstance {},
	Milesimos: class extends self.ITextInstance {},
	Segundos: class extends self.ITextInstance {},
	Tempo: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Texto2: class extends self.ITextInstance {},
	TempFinal: class extends self.ITextInstance {}
}